class BaseError(Exception):
    pass


class UnexpectedError(BaseException):
    pass
